frontend = container adminPortal "Frontend web application" "React, TypeScript, Vite" "User-facing administrative portal UI."
backendApi = container adminPortal "Backend HTTP API" "Python, FastAPI, Azure Functions adapters and ASGI runtime" "Environment, schedule, and operational HTTP APIs."
schedulerTimer = container adminPortal "Scheduler timer" "Python, Azure Functions timer trigger" "Finds due schedules and enqueues execution work."
schedulerWorker = container adminPortal "Scheduler worker" "Python, Azure Functions queue trigger" "Processes queued schedule actions and records audit events."
sharedDomain = container adminPortal "Shared backend layer" "Python shared modules" "Shared domain models, storage integration, auth helpers, and reusable backend logic."

frontend -> backendApi "Calls"
backendApi -> sharedDomain "Uses"
schedulerTimer -> sharedDomain "Uses"
schedulerWorker -> sharedDomain "Uses"

backendApi -> entraId "Validates tokens against"
backendApi -> tableStorage "Reads and writes table-backed data and audit events"
backendApi -> cosmosDb "Reads and writes schedule data and optional environment data"
schedulerTimer -> cosmosDb "Reads due schedules from"
schedulerTimer -> queueStorage "Enqueues due work into"
schedulerWorker -> queueStorage "Consumes scheduled work from"
schedulerWorker -> backendApi "Invokes environment action APIs on"
schedulerWorker -> tableStorage "Appends audit events to"
backendApi -> managedAzureResources "Controls or emits messages to"
schedulerWorker -> managedAzureResources "Triggers actions against via backend APIs"
backendApi -> keyVault "Reads runtime secrets through"
backendApi -> appInsights "Emits telemetry to"

