export const themeClasses = {
  shell: 'ui-shell',
  panel: 'ui-panel',
  panelMuted: 'ui-panel-muted',
  topbar: 'ui-topbar',
  sidebar: 'ui-sidebar',
  sidebarHeader: 'ui-sidebar-header',
  navItem: 'ui-nav-item',
  navItemActive: 'ui-nav-item-active',
  navSubmenu: 'ui-submenu',
  iconButton: 'ui-icon-button',
  field: 'ui-field',
  select: 'ui-select',
  buttonSecondary: 'ui-button-secondary',
  buttonPrimary: 'ui-button-primary',
  badge: 'ui-badge',
  textMuted: 'ui-text-muted',
  divider: 'ui-divider',
} as const;
